"""
Radar de Shorts Virais - YouTube Data API v3
----------------------------------------------
Busca Shorts verticais (9:16), com no maximo 25s de duracao, publicados
nas ultimas 30 dias, em ingles, espanhol, frances, alemao e italiano, com
pelo menos 500.000 visualizacoes dentro dessa janela e definicao HD
(melhor aproximacao disponivel na API para "Full HD ou superior" -- a
API nao expoe a resolucao exata em pixels). A busca ja mira no nicho de
curiosidades (termos como "did you know", "dato curioso" etc., em cada
idioma) e exige que o titulo/descricao bata essas palavras-chave,
exceto para os canais de referencia, que entram direto. Filtra fora
candidatos com termos tipicos de conteudo gerado por IA no
titulo/descricao.

Cada rodada SUBSTITUI o arquivo data.json inteiro pelos videos encontrados
NESSA rodada -- nao acumula com o que foi salvo em rodadas anteriores.
O log mostra quanto de cota da API cada rodada gasta, para voce saber
quantas vezes pode rodar de novo no mesmo dia.

Uso:
    export YOUTUBE_API_KEY="sua_chave_aqui"
    python fetch_shorts.py

Gera: data/data.json (consumido pelo dashboard index.html)
"""

import os
import re
import time
import json
import datetime
import requests

API_KEY = os.environ.get("YOUTUBE_API_KEY")
if not API_KEY:
    raise SystemExit("Defina a variavel de ambiente YOUTUBE_API_KEY antes de rodar.")

SEARCH_URL = "https://www.googleapis.com/youtube/v3/search"
VIDEOS_URL = "https://www.googleapis.com/youtube/v3/videos"
CHANNELS_URL = "https://www.googleapis.com/youtube/v3/channels"
PLAYLIST_ITEMS_URL = "https://www.googleapis.com/youtube/v3/playlistItems"

REQUEST_DELAY_SECONDS = 1.2        # pausa entre chamadas -- evita 429 (rate limit) da API
MAX_RETRIES = 5                    # tentativas extras se a API responder 429


class SearchQuotaExhausted(Exception):
    """Levantado quando a cota diaria ESPECIFICA de busca (Search Queries
    per day, hoje limitada a 100/dia pelo Google -- separada da cota
    geral de 10.000 unidades) se esgota. Tentar de novo nao ajuda ate a
    cota resetar (meia-noite no horario do Pacifico)."""
    pass


def api_get(url: str, params: dict) -> dict:
    """Faz uma chamada GET a API do YouTube com pausa entre requisicoes e
    nova tentativa automatica (com espera crescente) se a API responder
    429 por rajada de pedidos (rateLimitExceeded -- temporario). Se o
    erro for cota diaria de busca esgotada (quotaExceeded/dailyLimitExceeded),
    para na hora em vez de insistir a toa."""
    time.sleep(REQUEST_DELAY_SECONDS)
    for attempt in range(MAX_RETRIES + 1):
        resp = requests.get(url, params=params, timeout=30)
        if resp.status_code in (403, 429):
            reason = ""
            try:
                reason = resp.json().get("error", {}).get("errors", [{}])[0].get("reason", "")
            except (ValueError, KeyError, IndexError):
                pass

            if reason in ("quotaExceeded", "dailyLimitExceeded"):
                raise SearchQuotaExhausted(reason)

            wait = min(3 * (2 ** attempt), 60)
            print(f"429 recebido ({reason or 'sem motivo informado'}), aguardando {wait}s "
                  f"antes de tentar de novo (tentativa {attempt + 1}/{MAX_RETRIES})...")
            time.sleep(wait)
            continue
        resp.raise_for_status()
        return resp.json()
    resp.raise_for_status()  # se esgotou as tentativas, deixa o erro real aparecer
    return {}

HOURS_WINDOW = 30 * 24             # janela de tempo: 30 dias (publicado ha no maximo 720h)
# Termos de busca usados para ja mirar no nicho de curiosidades desde a
# origem (em vez de buscar generico e filtrar depois -- assim a maior
# parte do que chega ja e do nicho certo).
SEARCH_QUERIES = {
    "en": ["shorts did you know", "shorts fun facts", "shorts amazing facts"],
    "es": ["shorts dato curioso", "shorts sabías que", "shorts curiosidades"],
    "fr": ["shorts le saviez-vous", "shorts faits amusants", "shorts faits étonnants"],
    "de": ["shorts wusstest du", "shorts lustige fakten", "shorts erstaunliche fakten"],
    "it": ["shorts lo sapevi", "shorts curiosità", "shorts fatti incredibili"],
}
SEARCH_PAGES_PER_QUERY = 3         # paginas por termo de busca (50 resultados cada)
TOP_N = 200                        # teto alto -- na pratica, entrega tudo que passar nos filtros
MIN_VIEWS = 500_000                # views minimas DENTRO da janela (30 dias)
MAX_DURATION_SECONDS = 25          # duracao maxima do Short

# Termos que indicam conteudo gerado/narrado por IA -- filtro aproximado.
# Nao e 100% preciso (a API nao expoe isso diretamente), mas corta os casos obvios.
AI_KEYWORDS = [
    "ai generated", "made with ai", "created with ai", "ai voice",
    "midjourney", "sora ai", "runway ai", "pika ai", "generated by ai",
    "inteligencia artificial generada", "generado con ia", "creado con ia",
    "voz de ia", "hecho con ia",
]

# Termos que indicam nicho de curiosidades/fatos. So se aplica a videos
# fora dos canais de referencia (os canais de referencia ja SAO o nicho,
# entao entram direto sem precisar bater keyword no titulo/descricao).
NICHE_KEYWORDS = [
    "did you know", "fun fact", "fun facts", "weird fact", "weird facts",
    "amazing fact", "amazing facts", "mind blowing fact", "crazy fact",
    "crazy facts", "interesting fact", "interesting facts", "random fact",
    "random facts", "you didn't know", "science fact", "history fact",
    "curious fact", "curiosity", "did you ever wonder",
    "sabías que", "sabias que", "dato curioso", "datos curiosos",
    "curiosidad", "curiosidades", "no sabías", "no sabias",
    "dato increíble", "dato increible", "sabías esto", "sabias esto",
    "cosas que no sabías", "cosas que no sabias",
    "le saviez-vous", "saviez-vous que", "fait amusant", "faits amusants",
    "fait étonnant", "faits étonnants", "curiosité", "curiosités",
    "fait insolite", "faits insolites", "saviez vous",
    "wusstest du", "wusstest du schon", "lustige fakten",
    "erstaunliche fakten", "interessante fakten", "kuriosität",
    "kuriositäten", "wusstest du das",
    "lo sapevi", "lo sapevi che", "curiosità", "fatti incredibili",
    "fatto curioso", "fatti curiosi", "fatto sorprendente",
    "fatti sorprendenti",
]

# Canais de referencia que voce ja acompanha manualmente. O script busca
# os uploads recentes desses canais especificamente, alem da varredura
# geral por "Em alta". Handles sem o @ (o codigo adiciona na hora da API).
REFERENCE_CHANNELS = [
    "DanElCurioso",
    "QuikCuriosity",
    "ViiZ",
    "DailyDiscvr",
    "AprendeYDivierTT",
    "BoomCerebral-wp1nn",
    "ButchElSabio",
]
CHANNEL_RECENT_VIDEOS = 30         # quantos uploads recentes checar por canal (cobre ~1 mes)

# Filtros de PERFIL DE CANAL -- o objetivo e priorizar canais pequenos
# que estao estourando por causa do FORMATO/GANCHO, nao por audiencia ja
# consolidada. Nao se aplica aos canais de referencia (esses ja passaram
# no seu crivo manual e entram direto).
MAX_SUBSCRIBERS = 200_000          # acima disso, e considerado "canal grande" e excluido
POSTING_WINDOW_DAYS = 7            # janela usada para medir CONSTANCIA de postagem
MIN_UPLOADS_IN_WINDOW = 7          # exige quase 1 upload por dia na semana (canal muito ativo)
REPEAT_HIT_WINDOW_DAYS = 30        # janela usada para medir REPETICAO de acerto (~1 mes)
MIN_REPEAT_HITS = 1                # pelo menos 1 upload no periodo de 30 dias ja bateu um numero grande
REPEAT_HIT_VIEWS_THRESHOLD = 300_000    # o que conta como "vídeo grande" nesse historico


def iso_duration_to_seconds(duration: str) -> int:
    """Converte duracao ISO 8601 (ex: PT45S, PT1M5S) para segundos."""
    match = re.match(
        r"PT(?:(?P<h>\d+)H)?(?:(?P<m>\d+)M)?(?:(?P<s>\d+)S)?", duration
    )
    if not match:
        return 0
    parts = match.groupdict()
    h = int(parts["h"] or 0)
    m = int(parts["m"] or 0)
    s = int(parts["s"] or 0)
    return h * 3600 + m * 60 + s


def is_vertical(thumbnails: dict) -> bool:
    """Estimativa de formato 9:16 a partir das dimensoes da thumbnail."""
    thumb = thumbnails.get("maxres") or thumbnails.get("high") or thumbnails.get("default")
    if not thumb:
        return False
    width = thumb.get("width", 0)
    height = thumb.get("height", 0)
    if not width or not height:
        return False
    return height > width  # vertical = mais alto que largo


def looks_like_ai(title: str, description: str) -> bool:
    text = f"{title} {description}".lower()
    return any(term in text for term in AI_KEYWORDS)


def looks_like_niche(title: str, description: str) -> bool:
    text = f"{title} {description}".lower()
    return any(term in text for term in NICHE_KEYWORDS)


def fetch_video_details(video_ids: list) -> list:
    """Busca estatisticas + duracao para uma lista de IDs (lotes de 50)."""
    details = []
    for i in range(0, len(video_ids), 50):
        batch = video_ids[i:i + 50]
        params = {
            "part": "snippet,contentDetails,statistics",
            "id": ",".join(batch),
            "key": API_KEY,
        }
        data = api_get(VIDEOS_URL, params)
        details.extend(data.get("items", []))
    return details


def fetch_subscriber_counts(channel_ids: list) -> dict:
    """Busca o numero de inscritos de varios canais de uma vez (lotes de
    50). Retorna {channelId: subscriberCount ou None se o canal esconder
    esse numero publicamente}."""
    result = {}
    unique_ids = list(dict.fromkeys(channel_ids))  # remove duplicatas, mantem ordem
    for i in range(0, len(unique_ids), 50):
        batch = unique_ids[i:i + 50]
        params = {
            "part": "statistics",
            "id": ",".join(batch),
            "key": API_KEY,
        }
        data = api_get(CHANNELS_URL, params)
        for item in data.get("items", []):
            stats = item.get("statistics", {})
            if stats.get("hiddenSubscriberCount"):
                result[item["id"]] = None  # canal esconde o numero publicamente
            else:
                result[item["id"]] = int(stats.get("subscriberCount", 0))
    return result


def resolve_channel_id(handle: str) -> str | None:
    """Converte um @handle no channelId interno do YouTube."""
    params = {
        "part": "id",
        "forHandle": f"@{handle}",
        "key": API_KEY,
    }
    data = api_get(CHANNELS_URL, params)
    items = data.get("items", [])
    return items[0]["id"] if items else None


def get_uploads_playlist_id(channel_id: str) -> str | None:
    params = {
        "part": "contentDetails",
        "id": channel_id,
        "key": API_KEY,
    }
    data = api_get(CHANNELS_URL, params)
    items = data.get("items", [])
    if not items:
        return None
    return items[0]["contentDetails"]["relatedPlaylists"]["uploads"]


def analyze_channel_profile(channel_id: str, now: datetime.datetime) -> dict:
    """Analisa os uploads recentes de um canal para medir: (1) constancia
    de postagem nos ultimos POSTING_WINDOW_DAYS (padrao 7 dias), e (2)
    quantos uploads dos ultimos REPEAT_HIT_WINDOW_DAYS (padrao 30 dias)
    ja bateram um numero grande de views -- ou seja, se o canal REPETE
    acertos, e nao teve so um golpe de sorte isolado."""
    uploads_playlist_id = get_uploads_playlist_id(channel_id)
    if not uploads_playlist_id:
        return {"uploads_in_window": 0, "repeat_hits": 0}

    params = {
        "part": "contentDetails",
        "playlistId": uploads_playlist_id,
        "maxResults": CHANNEL_RECENT_VIDEOS,
        "key": API_KEY,
    }
    data = api_get(PLAYLIST_ITEMS_URL, params)
    video_ids = [
        i["contentDetails"]["videoId"]
        for i in data.get("items", [])
    ]
    if not video_ids:
        return {"uploads_in_window": 0, "repeat_hits": 0}

    details = fetch_video_details(video_ids)
    uploads_in_window = 0
    repeat_hits = 0
    for item in details:
        published_dt = datetime.datetime.strptime(
            item["snippet"]["publishedAt"], "%Y-%m-%dT%H:%M:%SZ"
        ).replace(tzinfo=datetime.timezone.utc)
        days_ago = (now - published_dt).days

        if days_ago <= POSTING_WINDOW_DAYS:
            uploads_in_window += 1

        if days_ago <= REPEAT_HIT_WINDOW_DAYS:
            views = int(item.get("statistics", {}).get("viewCount", 0))
            if views >= REPEAT_HIT_VIEWS_THRESHOLD:
                repeat_hits += 1

    return {"uploads_in_window": uploads_in_window, "repeat_hits": repeat_hits}


def fetch_reference_channel_videos(handle: str) -> list:
    """Busca os uploads recentes de um canal de referencia e retorna os
    detalhes completos (mesmo formato usado pelos videos do trending)."""
    channel_id = resolve_channel_id(handle)
    if not channel_id:
        print(f"[ref:{handle}] canal nao encontrado (handle incorreto?)")
        return []

    uploads_playlist_id = get_uploads_playlist_id(channel_id)
    if not uploads_playlist_id:
        print(f"[ref:{handle}] playlist de uploads nao encontrada")
        return []

    params = {
        "part": "contentDetails",
        "playlistId": uploads_playlist_id,
        "maxResults": CHANNEL_RECENT_VIDEOS,
        "key": API_KEY,
    }
    data = api_get(PLAYLIST_ITEMS_URL, params)
    video_ids = [
        i["contentDetails"]["videoId"]
        for i in data.get("items", [])
    ]
    if not video_ids:
        return []

    details = fetch_video_details(video_ids)
    for item in details:
        item["_language"] = ""
        item["_region"] = "canal_referencia"
        item["_isReference"] = True
    print(f"[ref:{handle}] {len(details)} uploads recentes encontrados")
    return details


def fetch_shorts_search(language: str, query: str, published_after: str) -> list:
    """Busca vídeos usando um termo focado no nicho (ex: 'shorts fun
    facts'), publicados na janela de tempo, ordenados por visualizacoes."""
    video_ids = []
    page_token = None
    for _ in range(SEARCH_PAGES_PER_QUERY):
        params = {
            "part": "id",
            "q": query,
            "type": "video",
            "order": "viewCount",
            "publishedAfter": published_after,
            "relevanceLanguage": language,
            "videoDuration": "short",  # <4min (filtramos <=25s depois)
            "maxResults": 50,
            "key": API_KEY,
        }
        if page_token:
            params["pageToken"] = page_token
        data = api_get(SEARCH_URL, params)
        for item in data.get("items", []):
            vid = item.get("id", {}).get("videoId")
            if vid:
                video_ids.append(vid)
        page_token = data.get("nextPageToken")
        if not page_token:
            break

    if not video_ids:
        return []

    details = fetch_video_details(video_ids)
    for item in details:
        item["_language"] = language
        item["_region"] = "busca_shorts"
        item["_isReference"] = False
    return details


def main():
    now = datetime.datetime.now(datetime.timezone.utc)
    published_after = (now - datetime.timedelta(hours=HOURS_WINDOW)).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )

    seen_ids = set()
    raw_items = []
    search_quota_hit = False
    for lang, queries in SEARCH_QUERIES.items():
        if search_quota_hit:
            break
        for query in queries:
            try:
                batch = fetch_shorts_search(lang, query, published_after)
            except SearchQuotaExhausted:
                print("⚠️  Cota diaria de BUSCA (100/dia) esgotada. Pulando as "
                      "buscas restantes e seguindo so com o que ja foi coletado "
                      "+ canais de referencia. Essa cota reseta a meia-noite "
                      "no horario do Pacifico.")
                search_quota_hit = True
                break
            new_batch = [i for i in batch if i["id"] not in seen_ids]
            seen_ids.update(i["id"] for i in new_batch)
            raw_items.extend(new_batch)
            print(f"[{lang}] \"{query}\": {len(new_batch)} videos novos (total bruto)")

    for handle in REFERENCE_CHANNELS:
        batch = fetch_reference_channel_videos(handle)
        new_batch = [i for i in batch if i["id"] not in seen_ids]
        seen_ids.update(i["id"] for i in new_batch)
        raw_items.extend(new_batch)

    print(f"Total de videos coletados (trending + canais de referencia): {len(raw_items)}")

    reasons = {
        "duration": 0, "vertical": 0, "ai": 0, "niche": 0, "hd": 0,
        "window": 0, "views": 0,
    }

    results = []
    for item in raw_items:
        duration_s = iso_duration_to_seconds(item["contentDetails"]["duration"])
        if duration_s > MAX_DURATION_SECONDS:
            reasons["duration"] += 1
            continue  # passou dos 25s

        if not is_vertical(item["snippet"]["thumbnails"]):
            reasons["vertical"] += 1
            # nao bloqueia mais (thumbnail nem sempre reflete o formato real do
            # video) -- so contabiliza para diagnostico. O formato Short ja
            # e garantido pela busca com termo "shorts" + duracao <=25s.

        title = item["snippet"]["title"]
        description = item["snippet"].get("description", "")
        if looks_like_ai(title, description):
            reasons["ai"] += 1
            continue  # termos indicando conteudo de IA

        # Nicho "curiosidades": exige bater keyword no titulo/descricao,
        # EXCETO para os canais de referencia, que ja sao o nicho por definicao.
        if not item.get("_isReference", False) and not looks_like_niche(title, description):
            reasons["niche"] += 1
            continue

        # Resolucao: a API so expoe "hd" ou "sd" (nao ha campo para 1080p
        # exato). "hd" e a melhor aproximacao disponivel para Full HD+.
        if item["contentDetails"].get("definition") != "hd":
            reasons["hd"] += 1
            continue

        published_at = item["snippet"]["publishedAt"]
        published_dt = datetime.datetime.strptime(
            published_at, "%Y-%m-%dT%H:%M:%SZ"
        ).replace(tzinfo=datetime.timezone.utc)
        hours_since_publish = (now - published_dt).total_seconds() / 3600
        if hours_since_publish > HOURS_WINDOW:
            reasons["window"] += 1
            continue  # publicado ha mais de 30 dias
        hours_since_publish = max(hours_since_publish, 0.5)

        stats = item.get("statistics", {})
        views = int(stats.get("viewCount", 0))
        if views < MIN_VIEWS:
            reasons["views"] += 1
            continue  # nao bateu o minimo de 500k dentro da janela

        velocity = views / hours_since_publish  # views por hora (info extra)

        results.append({
            "id": item["id"],
            "title": title,
            "channel": item["snippet"]["channelTitle"],
            "language": item["_language"],
            "region": item["_region"],
            "referenceChannel": item.get("_isReference", False),
            "publishedAt": published_at,
            "hoursSincePublish": round(hours_since_publish, 1),
            "views": views,
            "likes": int(stats.get("likeCount", 0)),
            "comments": int(stats.get("commentCount", 0)),
            "durationSeconds": duration_s,
            "velocity": round(velocity),
            "thumbnail": item["snippet"]["thumbnails"].get("high", {}).get(
                "url", item["snippet"]["thumbnails"]["default"]["url"]
            ),
            "url": f"https://www.youtube.com/shorts/{item['id']}",
        })

    print("Motivos de descarte:", reasons)

    # Busca o numero de inscritos de cada canal presente nos resultados finais
    result_ids = {r["id"] for r in results}
    id_to_channel_id = {item["id"]: item["snippet"]["channelId"] for item in raw_items}
    channel_ids = [id_to_channel_id[rid] for rid in result_ids]
    subscriber_map = fetch_subscriber_counts(channel_ids)
    for r in results:
        r["subscribers"] = subscriber_map.get(id_to_channel_id.get(r["id"]))

    # --- Filtros de PERFIL DE CANAL ---
    # Objetivo: priorizar canais pequenos que estao estourando por causa do
    # FORMATO/GANCHO, nao por audiencia ja consolidada. Canais de referencia
    # pulam esses filtros (ja passaram no seu crivo manual).
    reasons["subs_cap"] = 0
    reasons["consistency"] = 0
    filtered_results = []
    channel_profile_cache = {}
    for r in results:
        if r["referenceChannel"]:
            r["outlierScore"] = round(r["views"] / max(r["subscribers"] or 1, 1000), 1)
            filtered_results.append(r)
            continue

        subs = r["subscribers"]
        if subs is not None and subs > MAX_SUBSCRIBERS:
            reasons["subs_cap"] += 1
            continue  # canal grande demais -- audiencia consolidada, nao e sinal de formato bom

        ch_id = id_to_channel_id.get(r["id"])
        if ch_id not in channel_profile_cache:
            channel_profile_cache[ch_id] = analyze_channel_profile(ch_id, now)
        profile = channel_profile_cache[ch_id]

        if profile["uploads_in_window"] < MIN_UPLOADS_IN_WINDOW:
            reasons["consistency"] += 1
            continue  # canal nao posta com constancia -- pode ter sido sorte isolada

        if profile["repeat_hits"] < MIN_REPEAT_HITS:
            reasons["consistency"] += 1
            continue  # canal ainda nao repetiu o acerto -- pode ter sido sorte isolada

        r["channelUploadsLast7d"] = profile["uploads_in_window"]
        r["channelRepeatHits"] = profile["repeat_hits"]
        r["outlierScore"] = round(r["views"] / max(subs or 1, 1000), 1)
        filtered_results.append(r)

    results = filtered_results
    print(f"Apos filtro de perfil de canal (teto {MAX_SUBSCRIBERS} inscritos, "
          f"postagem >= {MIN_UPLOADS_IN_WINDOW} em {POSTING_WINDOW_DAYS}d, "
          f"repeticao >= {MIN_REPEAT_HITS} hit(s) de {REPEAT_HIT_VIEWS_THRESHOLD} views "
          f"em {REPEAT_HIT_WINDOW_DAYS}d): {len(results)} videos restantes")

    results.sort(key=lambda x: x["outlierScore"], reverse=True)
    top_results = results[:TOP_N]

    # Estimativa de cota gasta nesta rodada (para voce saber quantas vezes
    # por dia pode rodar sem estourar as 10.000 unidades gratuitas/dia).
    n_queries = sum(len(q) for q in SEARCH_QUERIES.values())
    estimated_quota = (n_queries * SEARCH_PAGES_PER_QUERY * 100) + 100
    print(f"Cota estimada usada nesta rodada: ~{estimated_quota} unidades "
          f"(cota gratuita diaria: 10.000 -- da para rodar mais "
          f"{10_000 // estimated_quota - 1} vez(es) hoje com folga)")

    output = {
        "generatedAt": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "windowHours": HOURS_WINDOW,
        "count": len(top_results),
        "videos": top_results,
    }

    os.makedirs("data", exist_ok=True)
    with open("data/data.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    print(f"OK - {len(top_results)} videos salvos em data/data.json")


if __name__ == "__main__":
    main()
