"""
Radar de Shorts Virais - YouTube Data API v3
----------------------------------------------
Busca Shorts verticais (9:16), com no maximo 25s de duracao, publicados
nas ultimas 48h, em ingles e espanhol, com pelo menos 500.000
visualizacoes dentro dessa janela e definicao HD (melhor aproximacao
disponivel na API para "Full HD ou superior" -- a API nao expoe a
resolucao exata em pixels). Filtra fora candidatos com termos tipicos
de conteudo gerado por IA no titulo/descricao.

Uso:
    export YOUTUBE_API_KEY="sua_chave_aqui"
    python fetch_shorts.py

Gera: data/data.json (consumido pelo dashboard index.html)
"""

import os
import re
import json
import datetime
import requests

API_KEY = os.environ.get("YOUTUBE_API_KEY")
if not API_KEY:
    raise SystemExit("Defina a variavel de ambiente YOUTUBE_API_KEY antes de rodar.")

SEARCH_URL = "https://www.googleapis.com/youtube/v3/search"
VIDEOS_URL = "https://www.googleapis.com/youtube/v3/videos"
CHANNELS_URL = "https://www.googleapis.com/youtube/v3/channels"
PLAYLIST_ITEMS_URL = "https://www.googleapis.com/youtube/v3/playlistItems"

LANGUAGES = ["en", "es"]           # ingles e espanhol
HOURS_WINDOW = 48                  # janela de tempo (publicado ha no maximo 48h)
SEARCH_PAGES = 3                   # paginas de busca por idioma (50 resultados cada)
TOP_N = 30                         # quantos videos entregar no final
MIN_VIEWS = 500_000                # views minimas DENTRO da janela de 48h
MAX_DURATION_SECONDS = 25          # duracao maxima do Short

# Termos que indicam conteudo gerado/narrado por IA -- filtro aproximado.
# Nao e 100% preciso (a API nao expoe isso diretamente), mas corta os casos obvios.
AI_KEYWORDS = [
    "ai generated", "made with ai", "created with ai", "ai voice",
    "midjourney", "sora ai", "runway ai", "pika ai", "generated by ai",
    "inteligencia artificial generada", "generado con ia", "creado con ia",
    "voz de ia", "hecho con ia",
]

# Canais de referencia que voce ja acompanha manualmente. O script busca
# os uploads recentes desses canais especificamente, alem da varredura
# geral por "Em alta". Handles sem o @ (o codigo adiciona na hora da API).
REFERENCE_CHANNELS = [
    "DanElCurioso",
    "QuikCuriosity",
    "ViiZ",
    "DailyDiscvr",
    "AprendeYDivierTT",
    "BoomCerebral-wp1nn",
    "ButchElSabio",
]
CHANNEL_RECENT_VIDEOS = 15         # quantos uploads recentes checar por canal


def iso_duration_to_seconds(duration: str) -> int:
    """Converte duracao ISO 8601 (ex: PT45S, PT1M5S) para segundos."""
    match = re.match(
        r"PT(?:(?P<h>\d+)H)?(?:(?P<m>\d+)M)?(?:(?P<s>\d+)S)?", duration
    )
    if not match:
        return 0
    parts = match.groupdict()
    h = int(parts["h"] or 0)
    m = int(parts["m"] or 0)
    s = int(parts["s"] or 0)
    return h * 3600 + m * 60 + s


def is_vertical(thumbnails: dict) -> bool:
    """Estimativa de formato 9:16 a partir das dimensoes da thumbnail."""
    thumb = thumbnails.get("maxres") or thumbnails.get("high") or thumbnails.get("default")
    if not thumb:
        return False
    width = thumb.get("width", 0)
    height = thumb.get("height", 0)
    if not width or not height:
        return False
    return height > width  # vertical = mais alto que largo


def looks_like_ai(title: str, description: str) -> bool:
    text = f"{title} {description}".lower()
    return any(term in text for term in AI_KEYWORDS)


def fetch_video_details(video_ids: list) -> list:
    """Busca estatisticas + duracao para uma lista de IDs (lotes de 50)."""
    details = []
    for i in range(0, len(video_ids), 50):
        batch = video_ids[i:i + 50]
        params = {
            "part": "snippet,contentDetails,statistics",
            "id": ",".join(batch),
            "key": API_KEY,
        }
        resp = requests.get(VIDEOS_URL, params=params, timeout=30)
        resp.raise_for_status()
        details.extend(resp.json().get("items", []))
    return details


def resolve_channel_id(handle: str) -> str | None:
    """Converte um @handle no channelId interno do YouTube."""
    params = {
        "part": "id",
        "forHandle": f"@{handle}",
        "key": API_KEY,
    }
    resp = requests.get(CHANNELS_URL, params=params, timeout=30)
    resp.raise_for_status()
    items = resp.json().get("items", [])
    return items[0]["id"] if items else None


def get_uploads_playlist_id(channel_id: str) -> str | None:
    params = {
        "part": "contentDetails",
        "id": channel_id,
        "key": API_KEY,
    }
    resp = requests.get(CHANNELS_URL, params=params, timeout=30)
    resp.raise_for_status()
    items = resp.json().get("items", [])
    if not items:
        return None
    return items[0]["contentDetails"]["relatedPlaylists"]["uploads"]


def fetch_reference_channel_videos(handle: str) -> list:
    """Busca os uploads recentes de um canal de referencia e retorna os
    detalhes completos (mesmo formato usado pelos videos do trending)."""
    channel_id = resolve_channel_id(handle)
    if not channel_id:
        print(f"[ref:{handle}] canal nao encontrado (handle incorreto?)")
        return []

    uploads_playlist_id = get_uploads_playlist_id(channel_id)
    if not uploads_playlist_id:
        print(f"[ref:{handle}] playlist de uploads nao encontrada")
        return []

    params = {
        "part": "contentDetails",
        "playlistId": uploads_playlist_id,
        "maxResults": CHANNEL_RECENT_VIDEOS,
        "key": API_KEY,
    }
    resp = requests.get(PLAYLIST_ITEMS_URL, params=params, timeout=30)
    resp.raise_for_status()
    video_ids = [
        i["contentDetails"]["videoId"]
        for i in resp.json().get("items", [])
    ]
    if not video_ids:
        return []

    details = fetch_video_details(video_ids)
    for item in details:
        item["_language"] = ""
        item["_region"] = "canal_referencia"
        item["_isReference"] = True
    print(f"[ref:{handle}] {len(details)} uploads recentes encontrados")
    return details


def fetch_shorts_search(language: str, published_after: str) -> list:
    """Busca vídeos marcados como #shorts, publicados na janela de tempo,
    ordenados por visualizacoes. Usar '#shorts' como termo de busca (em vez
    de nao usar 'q' nenhum) e o que garante que a API devolva resultados
    -- sem 'q', o endpoint de busca do YouTube retorna lista vazia."""
    video_ids = []
    page_token = None
    for _ in range(SEARCH_PAGES):
        params = {
            "part": "id",
            "q": "#shorts",
            "type": "video",
            "order": "viewCount",
            "publishedAfter": published_after,
            "relevanceLanguage": language,
            "videoDuration": "short",  # <4min (filtramos <=25s depois)
            "maxResults": 50,
            "key": API_KEY,
        }
        if page_token:
            params["pageToken"] = page_token
        resp = requests.get(SEARCH_URL, params=params, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        for item in data.get("items", []):
            vid = item.get("id", {}).get("videoId")
            if vid:
                video_ids.append(vid)
        page_token = data.get("nextPageToken")
        if not page_token:
            break

    if not video_ids:
        return []

    details = fetch_video_details(video_ids)
    for item in details:
        item["_language"] = language
        item["_region"] = "busca_shorts"
        item["_isReference"] = False
    return details


def main():
    now = datetime.datetime.now(datetime.timezone.utc)
    published_after = (now - datetime.timedelta(hours=HOURS_WINDOW)).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )

    seen_ids = set()
    raw_items = []
    for lang in LANGUAGES:
        batch = fetch_shorts_search(lang, published_after)
        new_batch = [i for i in batch if i["id"] not in seen_ids]
        seen_ids.update(i["id"] for i in new_batch)
        raw_items.extend(new_batch)
        print(f"[{lang}] {len(new_batch)} videos novos (total bruto)")

    for handle in REFERENCE_CHANNELS:
        batch = fetch_reference_channel_videos(handle)
        new_batch = [i for i in batch if i["id"] not in seen_ids]
        seen_ids.update(i["id"] for i in new_batch)
        raw_items.extend(new_batch)

    print(f"Total de videos coletados (trending + canais de referencia): {len(raw_items)}")

    reasons = {
        "duration": 0, "vertical": 0, "ai": 0, "hd": 0,
        "window": 0, "views": 0,
    }

    results = []
    for item in raw_items:
        duration_s = iso_duration_to_seconds(item["contentDetails"]["duration"])
        if duration_s > MAX_DURATION_SECONDS:
            reasons["duration"] += 1
            continue  # passou dos 25s

        if not is_vertical(item["snippet"]["thumbnails"]):
            reasons["vertical"] += 1
            # nao bloqueia mais (thumbnail nem sempre reflete o formato real do
            # video) -- so contabiliza para diagnostico. O formato Short ja
            # e garantido pela busca por #shorts + duracao <=25s.

        title = item["snippet"]["title"]
        description = item["snippet"].get("description", "")
        if looks_like_ai(title, description):
            reasons["ai"] += 1
            continue  # termos indicando conteudo de IA

        # Resolucao: a API so expoe "hd" ou "sd" (nao ha campo para 1080p
        # exato). "hd" e a melhor aproximacao disponivel para Full HD+.
        if item["contentDetails"].get("definition") != "hd":
            reasons["hd"] += 1
            continue

        published_at = item["snippet"]["publishedAt"]
        published_dt = datetime.datetime.strptime(
            published_at, "%Y-%m-%dT%H:%M:%SZ"
        ).replace(tzinfo=datetime.timezone.utc)
        hours_since_publish = (now - published_dt).total_seconds() / 3600
        if hours_since_publish > HOURS_WINDOW:
            reasons["window"] += 1
            continue  # publicado ha mais de 48h
        hours_since_publish = max(hours_since_publish, 0.5)

        stats = item.get("statistics", {})
        views = int(stats.get("viewCount", 0))
        if views < MIN_VIEWS:
            reasons["views"] += 1
            continue  # nao bateu o minimo de 500k dentro da janela

        velocity = views / hours_since_publish  # views por hora (info extra)

        results.append({
            "id": item["id"],
            "title": title,
            "channel": item["snippet"]["channelTitle"],
            "language": item["_language"],
            "region": item["_region"],
            "referenceChannel": item.get("_isReference", False),
            "publishedAt": published_at,
            "hoursSincePublish": round(hours_since_publish, 1),
            "views": views,
            "likes": int(stats.get("likeCount", 0)),
            "comments": int(stats.get("commentCount", 0)),
            "durationSeconds": duration_s,
            "velocity": round(velocity),
            "thumbnail": item["snippet"]["thumbnails"].get("high", {}).get(
                "url", item["snippet"]["thumbnails"]["default"]["url"]
            ),
            "url": f"https://www.youtube.com/shorts/{item['id']}",
        })

    print("Motivos de descarte:", reasons)
    results.sort(key=lambda x: x["views"], reverse=True)
    top_results = results[:TOP_N]

    output = {
        "generatedAt": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "windowHours": HOURS_WINDOW,
        "count": len(top_results),
        "videos": top_results,
    }

    os.makedirs("data", exist_ok=True)
    with open("data/data.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    print(f"OK - {len(top_results)} videos salvos em data/data.json")


if __name__ == "__main__":
    main()
